### PR TITLE
Add updated gnome-software ebuild

### PR DESCRIPTION
**Pull request by filmor**
This adds flatpak support to the upstream gnome-software ebuild, which makes the application much more useful.

### CODE REVIEW

**Comment by fosero** [comment]
When I started this repo I was actually thinking about adding gnome-software. I instead chose to keep this focused on the flatpak nuts and bolts.

Adding gnome-software to me would mean that it would need to be up-to-date to really bring the latest flatpak features. Having it up-to-date would mean that it is 2 release cycles ahead of what is in the Gentoo tree, with all the potential dependencies involved that is a no-no for me.

If Gentoo wasn't so consistently multiple release cycles behind upstream it might be a better sell.

**Comment by filmor** [comment]
My idea was more to just shadow whatever is currently in portage. Version 3.30.6 is from Dec 2018, so not even that old and only one release cycle behind, it works fine with this ebuild (and is utterly useless without it ;)).

**Comment by fosero** [comment]
It is 2 cycles in a week :wink:

I agree that the usefulness of gnome-software increases. When I investigated this the flatpak support was in its infancy and bleeding edge. So I'll look into it again if it is feasible for me to support.

I do think I want to go with the latest stable upstream release if anywhere near possible though.

**Comment by filmor** [comment]
Any update?

**Comment by okias** [comment]
@filmor you may be interested in contributing to `::gnome-next` [1]  with it, since Flatpak got merged into community managed overlay `::guru` [2].

Also it would be really cool. Only small concern is cross overlay dependency, but for optional USE flag (not with `+flatpak` but `flatpak`) it could be done I suppose :)

[1] https://github.com/Heather/gentoo-gnome/
[2] https://wiki.gentoo.org/wiki/Project:GURU

**Pull request closed without merging**
