### PR TITLE
Bump version to 1.4.0

### PR DESCRIPTION
**Pull request by Br1ght0ne**
[Flatpak 1.4.0 release on GitHub](https://github.com/flatpak/flatpak/releases/tag/1.4.0)

### CODE REVIEW

**Comment by Br1ght0ne** [comment]
Hi @fosero, I couldn't find a way to contact you besides GitHub, so I'm writing to you here.

I'd like to propose my help with maintaining this overlay, as the recent development of it seems to have slowed down.

Flatpak has seen numerous improvements (especially some critical fixes for Gentoo-based systems) since 1.3.0 (currently at 1.3.4), and it would be great to have a centralized overlay for Flatpak.

I've tested 1.3.4 with my personal overlay - it works great, and I couldn't even `emerge` 1.2.4.

Leaving it for your consideration.

**Comment by fosero** [comment]
@filalex77 Hey, I have been busy with other projects and keeping up with the unstable releases has not been a high priority. I think the stable releases are fine for most people for daily usage at this point, while in the past they sometimes were too far behind to be useful.

I welcome any help, but I need to see some quality and dedication to give someone access, as this repo has become the defacto place for the flatpak ebuilds it seems. I have no time for dealing with problems I did not create :wink:.

So I'll check this ebuild asap and merge it if it is ok. Then if you provide quality work for the next (few) release(s) as well, I'll provide you with access. Sounds ok?

**Comment by Br1ght0ne** [comment]
@fosero Yes, sounds very reasonable. Thanks for your answer, I'd surely try to do great with next releases!

**Comment by Br1ght0ne** [comment]
@fosero I got really out-of-date with this PR, and forgot the commit message format. Flatpak just released at 1.4.0 (stable), so I made a different (cleaner) PR: #32.

**Pull request closed without merging**
