### PR TITLE
add kde-plasma/xdg-desktop-portal-kde

### PR DESCRIPTION
**Pull request by seiflek**

### CODE REVIEW

**Review by fosero — CHANGES_REQUESTED** [review]
Can you make the commit messages follow the Gentoo style?

```
kde-plasma/xdg-desktop-portal-kde: Add 5.12.6
```

Also, why do you provide 3 different versions? I am not up-to-date on KDE versioning, so just enlighten me please :smile:

And would you be willing to maintain these portals for the forseeable future? I am not sure if they will be picked up by upstream Gentoo any time soon, as there is no upstream movement on supporting flatpaks.

**Comment by seiflek** [comment]
three diffrent versions reflecting the upstream tree, 5.12.5 current stable, 5.12.6 current testing in hope to go next stable, 5.13.3 latest unstable ~arch, you can check with:

`gentoo ~ # ls -l /usr/portage/kde-plasma/kwin/`
`drwxr-xr-x 2 root root 4096 May 30 17:22 files`
`-rw-r--r-- 1 root root 2661 May 26 02:09 kwin-5.12.5.ebuild`
`-rw-r--r-- 1 root root 2663 Jun 27 22:09 kwin-5.12.6.ebuild`
`-rw-r--r-- 1 root root 2634 Jul 10 13:09 kwin-5.13.3.ebuild`
`-rw-r--r-- 1 root root 2748 Jul 10 14:39 Manifest`
`-rw-r--r-- 1 root root  410 Feb 20  2017 metadata.xml`

i see that you provide flatpak-0.10.4 as 'arch' and 0.99.3 as '~arch', and so people who use plasma and live on 'arch' will have a version equivalent to what they have downstrean and so does people who live on '~arch' :wink: 
also, i've pushed our ebuilds that we use locally into github which contain bubblewrap and pipewire, you can check them, and maybe we can merge them into your tree.

**Review by fosero — APPROVED** [review]

**Comment by fosero** [comment]
Where can I see those ebuilds exactly?

I am not against adding some minor stuff, bubblewrap being one that is sort of overdue. But I want to keep this repo focused and not add everything and the kitchen sink.

The main assurance that I need is that you step up to maintain the kde portals for now, not just add them now and bit rot after this.

**Comment by seiflek** [comment]
You can see the ebuilds [here](https://github.com/seiflek/flatpak-overlay).

I get that you don't wanna add everything in the kitchen sink, but i wouldn't have suggested that in first place if i didn't see the comments on the ebuilds:

> \# FIXME: split out bubblewrap.
> \# FIXME: Add pipewire support.
> \# FIXME: selinux should be use-flagged
and this one [xdg-desktop-portal-kde](https://github.com/fosero/flatpak-overlay/issues/12)

Instead, i could've just pushed them publicly to a local tree, but why reinventing the wheel since this tree is already good and functional and can be enhanced and also people already use it.
But if you're not interested, that's fine i get it, i'll just keep the tree up.

**Comment by fosero** [comment]
No, don't get me wrong, this would be nice to have. And just pipewire alone is alright to have. I added those fixme's partially to refer to things that can be added when it gets in Gentoo main tree.

**Comment by fosero** [comment]
I've added @seiflek to the repo collaborators, so you can merge this PR yourself and keep the ebuilds up-to-date.

Feel free to open pull requests for bubblewrap & pipewire, so they can be reviewed.

Thanks for your contributions so far.

**Comment by seiflek** [comment]
Sorry i'm a bit late, thanks for the feedback @fosero , i'll merge this for now.
Thanks for your efforts in keeping up this tree.

**Pull request merged**
